vich_uploader:
    db_driver: orm

    mappings:
        image_file:
            uri_prefix: /uploads
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
